// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTravelSpa.Models;

namespace TimeTravelSpa.Migrations
{
    [DbContext(typeof(TimeTravelContext))]
    partial class TimeTravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("TimeTravelSpa.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("PositionInTime");

                    b.Property<int?>("TransporterId");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("TimeTravelSpa.Models.Transporter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Transporters");
                });

            modelBuilder.Entity("TimeTravelSpa.Models.Passenger", b =>
                {
                    b.HasOne("TimeTravelSpa.Models.Transporter", "Transporter")
                        .WithMany("Passengers")
                        .HasForeignKey("TransporterId");
                });
#pragma warning restore 612, 618
        }
    }
}
